### ISSUE TITLE
Sample From API + A few other things

### ISSUE THREAD

**Issue by mvarat** [mvarat/whitespace#1]
I am getting an issue when I try to sample an artwork because it is being redirected and I guess there is a problem with the header - "which is disallowed for cross-origin requests that require preflight".

Another issue is that I can't figure out how to get an image because the key has a : in it.

Third issue, I can't figure out how to make another request from the response of the first request.

**Comment by rapala61** [comment]
3x1 special!

**Comment by rapala61** [comment]
add us as collaborators to your project!
