### ISSUE TITLE
422 Error + 

### ISSUE THREAD

**Issue by mvarat** [mvarat/whitespace#3]
I am getting a 422 error when I try to save the artwork to the api. I added the below to the applications controller but its still not working. 
protect_from_forgery with: :exception

Also, I am very confused with using nested resources with angular and would like to discuss. 

One more thing, I am getting a 500 error when I deployed my rails app to Heroku. It works perfectly on local host.

Help!!!!

**Comment by ajhofferber** [comment]
hey! I know we figured out the server error with heroku, but do you still have this first issue happening?
