### ISSUE TITLE
Drop Down Select Angular

### ISSUE THREAD

**Issue by mvarat** [mvarat/whitespace#4]
I am struggling to get the dropdown select working in angular. I know I need to make a get request to get the options for the drop down but I know I am doing this incorrectly.

https://docs.angularjs.org/api/ng/directive/select

**Comment by DZGoldman** [comment]
Still working on this?

**Comment by mvarat** [comment]
yes, i am very stuck!

**Comment by DZGoldman** [comment]
I'm on 3 - I can come up if you're heavily situated

**Comment by mvarat** [comment]
i can come down. be right there

**Comment by DZGoldman** [comment]
Cool, I'm in the common room by the windows

**Comment by DZGoldman** [comment]
done it! (please close)
